/// Generated by AssetsRefGenerator on 2022/03/01
// ignore_for_file: constant_identifier_names

class Res {
  static const String female = "assets/images/female.png";
  static const String futher_andboy = "assets/images/futher_andboy.jpg";
  static const String icons = "assets/fonts/icons.ttf";
  static const String jannah = "assets/fonts/jannah.ttf";
  static const String male = "assets/images/male.png";
  static const String test = "assets/test.json";
}
